export const menu = [
    {
        "keyword": "gazpacho",
        "name": "Гаспачо",
        "price": 195,
        "category": "soups",
        "kind": "veg",
        "count": "350 г",
        "image": "../../img/menu/soups/gazpacho.jpg"
    },
    {
        "keyword": "mushroom_soup",
        "name": "Грибной суп-пюре",
        "price": 185,
        "category": "soups",
        "kind": "veg",
        "count": "330 г",
        "image": "../../img/menu/soups/mushroom_soup.jpg"
    },
    {
        "keyword": "norwegian_soup",
        "name": "Норвежский суп",
        "price": 270,
        "category": "soups",
        "kind": "fish",
        "count": "330 г",
        "image": "../../img/menu/soups/norwegian_soup.jpg"
    },
    {
        "keyword": "chicken",
        "name": "Куриный суп",
        "price": 330,
        "category": "soups",
        "kind": "meat",
        "count": "350 г",
        "image": "../../img/menu/soups/chicken.jpg"
    },
    {
        "keyword": "ramen",
        "name": "Рамен",
        "price": 375,
        "category": "soups",
        "kind": "meat",
        "count": "425 г",
        "image": "../../img/menu/soups/ramen.jpg"
    },
    {
        "keyword": "tomyum",
        "name": "Том ям с креветками",
        "price": 650,
        "category": "soups",
        "kind": "fish",
        "count": "500 г",
        "image": "../../img/menu/soups/tomyum.jpg"
    },
    {
        "keyword": "fried_potatoes_with_mushrooms",
        "name": "Жареная картошка с грибами",
        "price": 150,
        "category": "main-course",
        "kind": "veg",
        "count": "250 г",
        "image": "../../img/menu/main_course/friedpotatoeswithmushrooms1.jpg"
    },
    {
        "keyword": "lasagna",
        "name": "Лазанья",
        "price": 385,
        "category": "main-course",
        "kind": "meat",
        "count": "310 г",
        "image": "../../img/menu/main_course/lasagna.jpg"
    },
    {
        "keyword": "chicken_cutlets_and_mashed_potatoes",
        "name": "Котлеты из курицы с картофельным пюре",
        "price": 225,
        "category": "main-course",
        "kind": "meat",
        "count": "280 г",
        "image": (
            "../../img/menu/main_course/chickencutletsandmashedpotatoes.jpg"
        )
    },
    {
        "keyword": "fishrice",
        "name": "Рыбная котлета с рисом и спаржей",
        "price": 320,
        "category": "main-course",
        "kind": "fish",
        "count": "270 г",
        "image": "../../img/menu/main_course/fishrice.jpg"
    },
    {
        "keyword": "pizza",
        "name": "Пицца Маргарита",
        "price": 450,
        "category": "main-course",
        "kind": "veg",
        "count": "470 г",
        "image": "../../img/menu/main_course/pizza.jpg"
    },
    {
        "keyword": "shrimp_pasta",
        "name": "Паста с креветками",
        "price": 340,
        "category": "main-course",
        "kind": "fish",
        "count": "280 г",
        "image": "../../img/menu/main_course/shrimppasta.jpg"
    },
    {
        "keyword": "orange_juice",
        "name": "Апельсиновый сок",
        "price": 120,
        "category": "beverages",
        "kind": "cold",
        "count": "300 мл",
        "image": "../../img/menu/beverages/orangejuice.jpg"
    },
    {
        "keyword": "apple_juice",
        "name": "Яблочный сок",
        "price": 90,
        "category": "beverages",
        "kind": "cold",
        "count": "300 мл",
        "image": "../../img/menu/beverages/applejuice.jpg"
    },
    {
        keyword: 'carrot_juice',
        name: 'Морковный сок',
        price: 110,
        category: 'beverages',
        "kind": "cold",
        count: '300 мл',
        image: '../../img/menu/beverages/carrotjuice.jpg',
    },
    {
        keyword: 'cappuccino',
        name: 'Капучино',
        price: 180,
        category: 'beverages',
        "kind": "hot",
        count: '300 мл',
        image: '../../img/menu/beverages/cappuccino.jpg',
    },
    {
        keyword: 'green_tea',
        name: 'Зеленый чай',
        price: 100,
        category: 'beverages',
        "kind": "hot",
        count: '300 мл',
        image: '../../img/menu/beverages/greentea.jpg',
    },
    {
        keyword: 'tea',
        name: 'Черный чай',
        price: 90,
        category: 'beverages',
        "kind": "hot",
        count: '300 мл',
        image: '../../img/menu/beverages/tea.jpg',
    },
    {
        keyword: 'caesar',
        name: 'Цезарь с цыпленком',
        price: 370,
        category: 'salads-starters',
        "kind": "meat",
        count: '220 мл',
        image: '../../img/menu/salads_starters/caesar.jpg',
    },
    {
        keyword: 'caprese',
        name: 'Капрезе с моцареллой',
        price: 350,
        category: 'salads-starters',
        "kind": "veg",
        count: '235 мл',
        image: '../../img/menu/salads_starters/caprese.jpg',
    },
    {
        keyword: 'frenchfries1',
        name: 'Картофель фри с соусом Цезарь',
        price: 280,
        category: 'salads-starters',
        "kind": "veg",
        count: '235 мл',
        image: '../../img/menu/salads_starters/frenchfries1.jpg',
    },
    {
        keyword: 'frenchfries2',
        name: 'Картофель фри с кетчупом',
        price: 260,
        category: 'salads-starters',
        "kind": "veg",
        count: '235 мл',
        image: '../../img/menu/salads_starters/frenchfries2.jpg',
    },
    {
        keyword: 'salad_with_egg',
        name: 'Корейский салат с овощами и яйцом',
        price: 330,
        category: 'salads-starters',
        "kind": "veg",
        count: '250 мл',
        image: '../../img/menu/salads_starters/saladwithegg.jpg',
    },
    {
        keyword: 'tunasalad',
        name: 'Салат с тунцом',
        price: 480,
        category: 'salads-starters',
        "kind": "fish",
        count: '250 мл',
        image: '../../img/menu/salads_starters/tunasalad.jpg',
    },
    {
        keyword: 'baklava',
        name: 'Пахвала',
        price: 220,
        category: 'desserts',
        "kind": "medium",
        count: '300 мл',
        image: '../../img/menu/desserts/baklava.jpg',
    },
    {
        keyword: 'checheesecake',
        name: 'Чизкейк',
        price: 240,
        category: 'desserts',
        "kind": "small",
        count: '125 мл',
        image: '../../img/menu/desserts/checheesecake.jpg',
    },
    {
        keyword: 'chocolate_cake',
        name: 'Шоколадный торт',
        price: 270,
        category: 'desserts',
        "kind": "small",
        count: '140 мл',
        image: '../../img/menu/desserts/chocolatecake.jpg',
    },
    {
        keyword: 'chocolate_cheesecake',
        name: 'Шоколадный чизкейк',
        price: 260,
        category: 'desserts',
        "kind": "small",
        count: '125 мл',
        image: '../../img/menu/desserts/chocolatecheesecake.jpg',
    },
    {
        keyword: 'donuts',
        name: 'Пончики (3 штуки)',
        price: 410,
        category: 'desserts',
        "kind": "medium",
        count: '350 мл',
        image: '../../img/menu/desserts/donuts.jpg',
    },
    {
        keyword: 'donuts2',
        name: 'Пончики (6 штуки)',
        price: 650,
        category: 'desserts',
        "kind": "big",
        count: '700 мл',
        image: '../../img/menu/desserts/donuts2.jpg',
    },
];